variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/server/.gradle"
  - export GRADLE_USER_HOME

cache:
  paths:
  - frontend/node_modules/
  - frontend/dist/
  - backend/build/
  - backend/.gradle/

stages:
  - testserver
  - testclient

testserver:
  image: gradle:alpine
  stage: testserver
  script: 
    - apk add --update sqlite
    - cd backend
    - chmod +x db_setup.sh
    - ls -al
    - sh db_setup.sh
    - gradle test

testclient:
  image: node:16
  stage: testclient
  script:
    - cd client
    - npm install --progress=false
    - npm run test:unit
